import os

os.system('sudo apt update')
os.system('sudo apt install docker.io -y')
os.system('sudo usermod -aG docker ubuntu')
os.system('sudo chown ubuntu /var/run/docker.sock')
os.system('sudo apt install docker-compose -y')
os.system('sudo apt install maven -y')
#os.system('sudo apt install default-jdk -y')
#os.system('sudo apt install git -y')
os.system('git clone https://github.com/mr-prince-x/project-IGI.git')
os.system('cd project-IGI')
os.system('sudo rm -rf angular-app')
os.system('sudo mkdir angular-app')
os.system('cd ..')
os.system('git clone https://github.com/damini111294/quantamsoft.git')
os.system('sudo mv quantamsoft/* project-IGI/angular-app/')
os.system('cd project-IGI/springboot-app')
os.system('mvn clean package')
os.system('docker build -t pune .')
os.system('cd ..')
print("Your machine is ready to use")
